/// Validation Op Fixture Generator
///
/// This test generates known-good byte fixtures for validation Ops,
/// and also tests deserializing JavaScript-generated bytes.
///
/// Run with: cargo test --test validation_op_fixtures -- --nocapture
use base64::{engine::general_purpose::STANDARD, Engine};
use holo_hash::{ActionHash, AgentPubKey, AnyLinkableHash, EntryHash};
use holochain_serialized_bytes::prelude::*;
use holochain_zome_types::prelude::*;

// Same deterministic values as the TypeScript fixture tests
fn make_hash32(seed: u8) -> [u8; 32] {
    [seed; 32]
}

fn make_agent_pubkey(seed: u8) -> AgentPubKey {
    AgentPubKey::from_raw_32(make_hash32(seed).to_vec())
}

fn make_action_hash(seed: u8) -> ActionHash {
    ActionHash::from_raw_32(make_hash32(seed).to_vec())
}

fn make_entry_hash(seed: u8) -> EntryHash {
    EntryHash::from_raw_32(make_hash32(seed).to_vec())
}

fn make_signature() -> Signature {
    Signature(vec![0xbb; 64].try_into().unwrap())
}

fn fixed_timestamp() -> Timestamp {
    // 2024-01-01 00:00:00 UTC in microseconds
    Timestamp(1704067200000000)
}

fn make_create_action() -> Action {
    Action::Create(Create {
        author: make_agent_pubkey(0x11),
        timestamp: fixed_timestamp(),
        action_seq: 5,
        prev_action: make_action_hash(0x22),
        entry_type: EntryType::App(AppEntryDef {
            entry_index: 0.into(),
            zome_index: 0.into(),
            visibility: EntryVisibility::Public,
        }),
        entry_hash: make_entry_hash(0x33),
        weight: EntryRateWeight::default(),
    })
}

fn make_create_link_action() -> Action {
    Action::CreateLink(CreateLink {
        author: make_agent_pubkey(0x11),
        timestamp: fixed_timestamp(),
        action_seq: 8,
        prev_action: make_action_hash(0x22),
        base_address: AnyLinkableHash::from(make_entry_hash(0x33)),
        target_address: AnyLinkableHash::from(make_entry_hash(0x44)),
        zome_index: 0.into(),
        link_type: 0.into(),
        tag: LinkTag::new(vec![0x01, 0x02, 0x03]),
        weight: RateWeight::default(),
    })
}

fn make_signed_action_hashed(action: Action) -> SignedActionHashed {
    SignedActionHashed::with_presigned(
        ActionHashed::with_pre_hashed(action, make_action_hash(0xaa)),
        make_signature(),
    )
}

fn make_entry() -> Entry {
    Entry::App(AppEntryBytes(SerializedBytes::from(UnsafeBytes::from(
        vec![1u8, 2, 3, 4, 5],
    ))))
}

#[test]
fn generate_store_record_op_fixture() {
    let action = make_create_action();
    let signed = make_signed_action_hashed(action);
    let record = Record::new(signed, Some(make_entry()));

    let op = Op::StoreRecord(StoreRecord { record });

    // Serialize using holochain_serialized_bytes (rmp-serde with struct_map)
    let inner_bytes = holochain_serialized_bytes::encode(&op).unwrap();
    println!("StoreRecord Op inner bytes ({} bytes):", inner_bytes.len());
    println!("  base64: {}", STANDARD.encode(&inner_bytes));
    println!(
        "  first 80 hex: {}",
        inner_bytes
            .iter()
            .take(80)
            .map(|b| format!("{b:02x}"))
            .collect::<String>()
    );

    // Also show ExternIO wrapping (what actually goes to WASM memory)
    let extern_io = ExternIO::encode(&op).unwrap();
    let extern_io_bytes = holochain_serialized_bytes::encode(&extern_io).unwrap();
    println!("\nExternIO-wrapped ({} bytes):", extern_io_bytes.len());
    println!("  base64: {}", STANDARD.encode(&extern_io_bytes));
    println!(
        "  first 20 hex: {}",
        extern_io_bytes
            .iter()
            .take(20)
            .map(|b| format!("{b:02x}"))
            .collect::<String>()
    );

    // Verify round-trip
    let decoded: Op = holochain_serialized_bytes::decode(&inner_bytes).unwrap();
    println!("\nRound-trip: OK");
    match &decoded {
        Op::StoreRecord(sr) => {
            let action = sr.record.action();
            println!("  Action type: {:?}", action.action_type());
        }
        _ => panic!("Wrong Op variant"),
    }
}

#[test]
fn generate_store_record_createlink_op_fixture() {
    let action = make_create_link_action();
    let signed = make_signed_action_hashed(action);
    let record = Record::new(signed, None);

    let op = Op::StoreRecord(StoreRecord { record });

    let inner_bytes = holochain_serialized_bytes::encode(&op).unwrap();
    println!(
        "StoreRecord (CreateLink) Op inner bytes ({} bytes):",
        inner_bytes.len()
    );
    println!("  base64: {}", STANDARD.encode(&inner_bytes));
    println!(
        "  first 80 hex: {}",
        inner_bytes
            .iter()
            .take(80)
            .map(|b| format!("{b:02x}"))
            .collect::<String>()
    );

    // Verify round-trip
    let decoded: Op = holochain_serialized_bytes::decode(&inner_bytes).unwrap();
    println!("Round-trip: OK");
}

#[test]
fn generate_store_entry_op_fixture() {
    let create = match make_create_action() {
        Action::Create(c) => c,
        _ => unreachable!(),
    };

    let entry = make_entry();

    let op = Op::StoreEntry(StoreEntry {
        action: SignedHashed::with_presigned(
            HoloHashed::with_pre_hashed(
                EntryCreationAction::Create(create),
                make_action_hash(0xaa),
            ),
            make_signature(),
        ),
        entry,
    });

    let inner_bytes = holochain_serialized_bytes::encode(&op).unwrap();
    println!("StoreEntry Op inner bytes ({} bytes):", inner_bytes.len());
    println!("  base64: {}", STANDARD.encode(&inner_bytes));
    println!(
        "  first 80 hex: {}",
        inner_bytes
            .iter()
            .take(80)
            .map(|b| format!("{b:02x}"))
            .collect::<String>()
    );

    // Verify round-trip
    let decoded: Op = holochain_serialized_bytes::decode(&inner_bytes).unwrap();
    println!("Round-trip: OK");
}

#[test]
fn generate_register_create_link_op_fixture() {
    let create_link = match make_create_link_action() {
        Action::CreateLink(cl) => cl,
        _ => unreachable!(),
    };

    let op = Op::RegisterCreateLink(RegisterCreateLink {
        create_link: SignedHashed::with_presigned(
            HoloHashed::with_pre_hashed(create_link, make_action_hash(0xaa)),
            make_signature(),
        ),
    });

    let inner_bytes = holochain_serialized_bytes::encode(&op).unwrap();
    println!(
        "RegisterCreateLink Op inner bytes ({} bytes):",
        inner_bytes.len()
    );
    println!("  base64: {}", STANDARD.encode(&inner_bytes));

    // Verify round-trip
    let decoded: Op = holochain_serialized_bytes::decode(&inner_bytes).unwrap();
    println!("Round-trip: OK");
}

#[test]
fn deserialize_js_store_record_create() {
    // JS-encoded StoreRecord (Create) Op bytes from TypeScript
    let js_b64 = "gatTdG9yZVJlY29yZIGmcmVjb3Jkgq1zaWduZWRfYWN0aW9ugqZoYXNoZWSCp2NvbnRlbnSIpHR5cGWmQ3JlYXRlpmF1dGhvcsQnhCAkERERERERERERERERERERERERERERERERERERERERERH9Qa+3qXRpbWVzdGFtcM8ABg3XECEgAKphY3Rpb25fc2VxBatwcmV2X2FjdGlvbsQnhCkkIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiK+E0lkqmVudHJ5X3R5cGWBo0FwcIOrZW50cnlfaW5kZXgAqnpvbWVfaW5kZXgAqnZpc2liaWxpdHmmUHVibGljqmVudHJ5X2hhc2jEJ4QhJDMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz2wLUX6Z3ZWlnaHSDqWJ1Y2tldF9pZACldW5pdHMAqnJhdGVfYnl0ZXMApGhhc2jEJ4QpJKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqx7IRFKlzaWduYXR1cmXEQLu7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7ulZW50cnmBp1ByZXNlbnSCqmVudHJ5X3R5cGWjQXBwpWVudHJ5xAUBAgMEBQ==";

    let js_bytes = STANDARD.decode(js_b64).unwrap();
    println!("JS StoreRecord (Create) bytes: {} bytes", js_bytes.len());

    let result: Result<Op, _> = holochain_serialized_bytes::decode(&js_bytes);
    match result {
        Ok(op) => {
            println!("SUCCESS: JS bytes deserialized to Op");
            match &op {
                Op::StoreRecord(sr) => {
                    let action = sr.record.action();
                    println!("  Action type: {:?}", action.action_type());
                    if let Action::Create(c) = action {
                        println!("  Author: {:?}", c.author);
                        println!("  Entry type: {:?}", c.entry_type);
                        println!("  Weight: {:?}", c.weight);
                    }
                }
                _ => println!("  Wrong variant: expected StoreRecord"),
            }
        }
        Err(e) => {
            println!("FAILED: {e}");
            // Show first 40 bytes as hex for debugging
            let hex: String = js_bytes
                .iter()
                .take(40)
                .map(|b| format!("{b:02x}"))
                .collect();
            println!("  First 40 bytes: {hex}");
        }
    }
}

#[test]
fn deserialize_js_store_record_createlink() {
    // JS-encoded StoreRecord (CreateLink) Op bytes from TypeScript
    let js_b64 = "gatTdG9yZVJlY29yZIGmcmVjb3Jkgq1zaWduZWRfYWN0aW9ugqZoYXNoZWSCp2NvbnRlbnSLpHR5cGWqQ3JlYXRlTGlua6ZhdXRob3LEJ4QgJBERERERERERERERERERERERERERERERERERERERERER/UGvt6l0aW1lc3RhbXDPAAYN1xAhIACqYWN0aW9uX3NlcQircHJldl9hY3Rpb27EJ4QpJCIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIivhNJZKxiYXNlX2FkZHJlc3PEJ4QhJDMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz2wLUX650YXJnZXRfYWRkcmVzc8QnhCEkRERERERERERERERERERERERERERERERERERERERERER7z3URqnpvbWVfaW5kZXgAqWxpbmtfdHlwZQCjdGFnxAMBAgOmd2VpZ2h0gqlidWNrZXRfaWQApXVuaXRzAKRoYXNoxCeEKSSqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqseyERSpc2lnbmF0dXJlxEC7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7pWVudHJ5ok5B";

    let js_bytes = STANDARD.decode(js_b64).unwrap();
    println!(
        "JS StoreRecord (CreateLink) bytes: {} bytes",
        js_bytes.len()
    );

    let result: Result<Op, _> = holochain_serialized_bytes::decode(&js_bytes);
    match result {
        Ok(op) => {
            println!("SUCCESS: JS bytes deserialized to Op");
            match &op {
                Op::StoreRecord(sr) => {
                    let action = sr.record.action();
                    println!("  Action type: {:?}", action.action_type());
                }
                _ => println!("  Wrong variant: expected StoreRecord"),
            }
        }
        Err(e) => {
            println!("FAILED: {e}");
        }
    }
}

#[test]
fn deserialize_js_register_create_link() {
    // JS-encoded RegisterCreateLink Op bytes from TypeScript
    let js_b64 = "gbJSZWdpc3RlckNyZWF0ZUxpbmuBq2NyZWF0ZV9saW5rgqZoYXNoZWSCp2NvbnRlbnSKpmF1dGhvcsQnhCAkERERERERERERERERERERERERERERERERERERERERERH9Qa+3qXRpbWVzdGFtcM8ABg3XECEgAKphY3Rpb25fc2VxCKtwcmV2X2FjdGlvbsQnhCkkIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiK+E0lkrGJhc2VfYWRkcmVzc8QnhCEkMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzPbAtRfrnRhcmdldF9hZGRyZXNzxCeEISRERERERERERERERERERERERERERERERERERERERERERHvPdRGqem9tZV9pbmRleACpbGlua190eXBlAKN0YWfEAwECA6Z3ZWlnaHSCqWJ1Y2tldF9pZACldW5pdHMApGhhc2jEJ4QpJKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqx7IRFKlzaWduYXR1cmXEQLu7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7s=";

    let js_bytes = STANDARD.decode(js_b64).unwrap();
    println!("JS RegisterCreateLink bytes: {} bytes", js_bytes.len());

    let result: Result<Op, _> = holochain_serialized_bytes::decode(&js_bytes);
    match result {
        Ok(op) => {
            println!("SUCCESS: JS bytes deserialized to Op");
            match &op {
                Op::RegisterCreateLink(rcl) => {
                    println!(
                        "  CreateLink zome_index: {:?}",
                        rcl.create_link.hashed.content.zome_index
                    );
                }
                _ => println!("  Wrong variant: expected RegisterCreateLink"),
            }
        }
        Err(e) => {
            println!("FAILED: {e}");
        }
    }
}
